package edu.rit.dbc.server;

import java.io.Serializable;
import java.rmi.RemoteException;
import java.rmi.registry.Registry;

/**
 * Template Class for the ContractProxy which will be generated by ProxyGenerator.java
 * @author Ashwin 
 *
 */
public abstract class AbstractContractProxy implements Serializable{

	private static final long serialVersionUID = 9023601923512562673L;

	public static Registry registry;
	
	public abstract void bind(String bind_name) throws RemoteException;
}
